### ISSUE TITLE
Active Item 1

### ISSUE THREAD

**Issue by 2xCmet** [danielspaniol/8BitToHell#18]
A bomb which will kill all Enemies in the Current Room(expect boss)

- [x] Basic Item (16x16)

**Comment by richardpolzer** [comment]
General Question on active Items: Should they have an activated state or an animation when active?

**Comment by 2xCmet** [comment]
Make a slightly greyer version for the time they are on CD

**Comment by 2xCmet** [comment]
We will render them slightly greyer ingame so no need for a second picture
