### ISSUE TITLE
Enemy - Crabby Patty

### ISSUE THREAD

**Issue by richardpolzer** [danielspaniol/8BitToHell#25]
- [x] Basic Enemy
- [x] Walking animation
- [x] Idle animation
- [x] Attack animation

![crabby patty](https://cloud.githubusercontent.com/assets/22379225/25120693/6de601a6-241f-11e7-9dc6-5960f19e4434.jpeg)

**Comment by danielspaniol** [comment]
I assume:
- The SpriteSheet is `animations/crabby.png`
- The SpriteSheet has a size of 5x5
- The animations are:
    - Idle: first row, 2 frames
    - Walk: second row, 3 frames
    - Jump: third row, 3 frames
    - Attack: fourth row, 3 frames
    - Die: fifth row, 3 frames

if any of the above is wrong please change the animations under `roguelike.assets::Animations`

**Comment by richardpolzer** [comment]
@danielspaniol What pixel size should one tile be? and are so many animations necessary?
